### ISSUE TITLE
pos_label=False

### ISSUE THREAD

**Issue by diogoff** [chat-analytics-for-twitch/evaluation#1]
The Task Description defines true positives as the user-channel combinations that are correctly identified as subscribed.

However, setting `pos_label=False` seems to imply that the true positives will be the user-channel combinations that are correctly identified as _not_ subscribed.

Which one is intended? Thanks.

**Comment by konstantinkobs** [comment]
Thank you for your question. We deleted the `pos_label=False` part now. We did that initially to allow a Majority Baseline that always predicts `False`, which would yield a F1 score of 0.0 with out the additional attribute. We will now remove or alter this baseline to make it more meaningful.
